### PR TITLE
Support Linux

### PR DESCRIPTION
**Pull request by ghost**
- Missing headers added in src/SkGui/src/declarative/private
- include paths in adjusted to use the headers that were missing
- SkMedia links w/ vlc on linux, libvlc on win32
- Fixed compilation error in WVlcPlayer.cpp (type mismatch)
- Dynamically link dependencies for SkTorrent on linux
- SkTorrent links w/ libtorrent-rasterbar on linux, libtorrent on win32

### CODE REVIEW

**Comment by ghost** [comment]
Here is a pull request for you to review, it has the changes that were necessary for me to build on Linux. I haven't tested the .so files it produced (I don't know if there is a test suite of any kind?)

I'd suggest checking to see if my changes still allow it to build and run fine on Windows before accepting the pull request.

**Review by 3unjee — COMMENTED** [review]
- The modified configure.sh is missing. Maybe you forgot it ?
- WDeclarative\* files should be copied by the configure script under the "include/Qt/QtDeclarative" folder. We are assuming the user has Qt sources under ../3rparty/Qt.
- SkMedia.pro: linux:LIBS and win32:LIBS could be written once outside the condition.
- WVlcPlayer.cpp: You could probably use (qint64) length instead of QVariant((qlonglong)length). That would be cleaner.

Thanks !

**Comment by 3unjee** [comment]
by "WDeclarative\* files" I meant "QDeclarative\* files".

**Comment by ghost** [comment]
Sounds good, I'll make those changes and submit a new pull request tonight!

**Pull request closed without merging**
