### PR TITLE
Support Linux

### PR DESCRIPTION
**Pull request by ghost**
- Updated configure.sh
- SkMedia links w/ vlc on linux, libvlc on win32
- Fixed compilation error in WVlcPlayer.cpp (type mismatch)
- Dynamically link dependencies for SkTorrent on linux
- SkTorrent links w/ libtorrent-rasterbar on linux, libtorrent on win32

### CODE REVIEW

**Comment by 3unjee** [comment]
Thank you miotatsu, it looks quite good. 

I'm currently busy with the 1.1.2 release. I'll keep you posted !

**Comment by 3unjee** [comment]
Merged ! You are the first Sky kit contributor \o/.

I would like to add you in the AUTHOR file:
- Mio Iwakura aka [miotatsu](http://miotatsu.github.io) | mio.iwakura@gmail.com

Are these informations correct ?

**Comment by 3unjee** [comment]
Also, I'm interested by the commands you run to retrieve the dependencies and build Sky kit.

Could you share them here ?

**Comment by ghost** [comment]
Yep that information is correct, Mio Iwakura is not actually my legal name, but I use it as a pseudonym online and prefer to be referred to by it.

Regarding the commands I run to retrieve the dependencies and build Sky kit:

```
# this command is Arch specific, other distros have their own package managers
sudo pacman -S qt4 qtwebkit vlc libtorrent-rasterbar boost openssl

# make folder for Sky, pull in qt4 source and Sky source
mkdir -p Sky/3rdparty
cd Sky
git clone https://code.qt.io/cgit/qt/qt.git 3rdparty/Qt
git clone https://github.com/omega-gg/Sky.git
cd Sky

# build Sky
sh ./configure.sh qt4 linux
# tell Qt4 to generate a makefile for Linux with g++ compiler
QMAKESPEC=/usr/share/qt4/mkspecs/linux-g++
# Arch installs qmake as qmake-qt4 so that qt4 can be installed alongside qt5 without conflict
qmake-qt4 -r
make
```

**Comment by 3unjee** [comment]
Thanks for that. Looking forward to add something like that in the configure script. Maybe I should have "archlinux" / "ubuntu" specific flags.

I did a few changes after the merge starting here: https://github.com/omega-gg/Sky/commit/bae6bb6198d5e6e7976d534bacb14d25465da566.

Let me know if it breaks anything.

**Pull request merged**
